### ISSUE TITLE
Get a months / then years worth of ETo data as a movie via EE

### ISSUE THREAD

**Issue by qjhart** [CSTARS/eto-zone-maps#4]
Earth Engine recently released new output format, movies! With this format, you can create a movie from a set of input images.  We should see if we can do this for our ETo zones maps.  One hurdle for this has been a convenient way of getting data into EE.  For rasters, this is via MapsEngine.  However, this is not an easily automated task, and it will be going away soon. However, @qjhart had an idea about this.  What if we made a single image with many bands, and then deconstructed the bands into an image collection once it was on Earth Engine?  
- [x] The idea would be to create a geotiff from a set of Grass images (@qjhart)
- [x] Upload that single image to  EE ( @jrmerz or @qjhart) via Maps Engine
- [x] Script a tool to convert to a movie (probably via image collection, haven't investigated)

If we do the 12 band months first, we can move on to a daily version.

**Comment by qjhart** [comment]
@jrmerz  I added you as an EE share to eto-zone-maps.  Example scripts with the 12 band monthly data.

**Comment by qjhart** [comment]
@jrmera, the example script in that EE share now includes a movie creation script.  Pretty simple.

**Comment by jrmerz** [comment]
@qjhart I don't see where I can load a shared workspace

**Comment by jrmerz** [comment]
@qjhart I might be missing some images, getting the following message when I try and run the script: Image.load: Asset 'GME/images/01792854546543828466-08785084107818230685' not found.
    in <global>, line 3

**Comment by qjhart** [comment]
Give it another try, I've made it public.
