### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by jlivni** [CSTARS/eto-zone-maps#8]
Hi, this project looks really interesting.  Do you mind to add a LICENSE file to the code and/or derived results here?

If it's something like Apache2 or MIT, I'd be keen to make use of it (and potentially contribute back if you're looking for that).

**Comment by qjhart** [comment]
MIT License Added.

@jlivni , Sorry this project was taking a bit of a hiatus, but we are now working on finalizing our maps.  If you are interested, let me know how you'd like to use this project, and I'll ask my state contacts about sharing the preliminary report and zone maps.

**Comment by jlivni** [comment]
Thanks Quinn!

I am working on a project (givinggarden.io) that aims to provide gardeners with recommendations on what grows in their area, and evapotranspiration is a key component to our model.  I have not looked at this code in depth, but at first glance I believe I can create the zone maps you're referring to with what you've already provided.

That said, if there's source data that's not publicly available and you are able to share the resulting maps under a CC style license, that would be fantastic.

I'm hoping to look at this more in a couple months and then will be happy to provide pull requests if anything comes up that would seem useful.
